TITLE = "Apartment Management System"
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 500
BACKGROUND_COLOUR = "#1c1c1c"
FOREGROUND_COLOUR = "#ffffff"

AVAILABILITY = "AVAILABILITY"
ON_RENT = "ON_RENT"
OWNER_NAME = "OWNER_NAME"
TENANT_NAME = "TENANT_NAME"
PHONE_NUMBER = "PHONE_NUMBER"
EMAIL = "EMAIL"
FLATS_OWNED = "FLATS_OWNED"
